server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/servicedesk_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=kEQI0IsfxCIGtLFL3dL64tOz9AM7vuxD0Gh5w2sN1O7RlG48sPJFHwWsfMFGj6SZIh1qv9D4HIpoENDYvXcAdQ==
app.jwt.expiration-ms=86400000